---
greeting: "Hello from group_vars/all"
db_password: "{{ vault_db_password }}"

# Hetzner Cloud Configuration (WIP)
my_hetzner_config:
  group: "mordor"
  name: "mount-doom"
  api_token: "{{ vault_hetzner_secrets.api_token }}"
  ssh_key:
    name: "{{ vault_hetzner_secrets.ssh_key.name }}"
  ansible_user:
    name: "morgoth"
    password: "{{ vault_hetzner_secrets.ansible_user.password }}"

desktop_users:
  - name: "sauron"
    password: "{{ vault_sauron.password }}"