---
greeting: "Hello from group_vars/all"
db_password: "{{ vault_db_password }}"

# Hetzner Cloud Configuration (WIP)
my_hetzner_config:
  group: "mordor"
  name: "mount-doom"
  api_token: "{{ vault_my_hetzner_api_token }}"
  ssh_key:
    name: "{{ vault_my_ssh_public.name }}"
    public_value: "{{ vault_my_ssh_public.key }}"
  ansible_user:
    name: "morgoth"
    password: "{{ vault_my_ansible_user_password }}"

desktop_users:
  - name: "sauron"
    password: "{{ vault_sauron.password }}"